name: Validate WDL workflow and task definitions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    # Allows manually triggering workflow in GitHub UI on selected branch.
    # GitHub doc: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_dispatch.
    # GitHub blog demo: https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/.

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Validate WDL
      run: |
        set -o errexit
        set -o pipefail
        set -o nounset
        set +o errexit
        
        wget --no-clobber --quiet https://github.com/broadinstitute/cromwell/releases/download/78/womtool-78.jar
        
        for WDL_FILE in $(find . -type f -name "*.wdl"); do
          java -jar womtool-78.jar validate ${WDL_FILE}
